spring.application.name=energy-formula-svc

#MVC Configuration
spring.mvc.hiddenmethod.filter.enabled=true

#MongoDB Configuration
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.data.mongodb.database=energy_formula_svc

server.port=${PORT:8080}

